// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmgxytkempjppknohoox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtZ3h5dGtlbXBqcHBrbm9ob294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjU4OTQsImV4cCI6MjA3NDU0MTg5NH0.Y3t1rzNC12eofA8PJ9poe43_hRfJobGeIKX619jc_to";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});